### ISSUE TITLE
SVG(filename='PICS/Sitemap.svg') missing

### ISSUE THREAD

**Issue by PKHG** [uds-se/fuzzingbook#50]
downloaded (all)
could not find PICS/Sitemap.svg  

Otherwise (super) fine notebooks 

Greets
    PKHG

**Comment by andreas-zeller** [comment]
Thanks!  This is now fixed - "fuzzingbook-notebooks.zip" now also contains "PICS/Sitemap.svg".

**Comment by PKHG** [comment]
Dear  Andreas
clone just some minutes ago the fuzzing notebook
The missing ... is yet not solved:
http://localhost:8888/notebooks/fuzzing_notebook/fuzzingbook/notebooks/Tours.ipynb
contains stil:
from IPython.display import SVG
no error
SVG(filename='PICS/Sitemap.svg')
delivers File not found ERROR???

That marvolous Sitemap picture I saw at  the WWW you wrote:
Solved but I can not see it locally.
The Sitemap was(is?) even interactive so is it really an SVG?

OK, if there is no easy info for me, let me know ...

Now starting again with studying.

By the way I was member of the University of Twente, The Netherlands, but
now not
anymore (77 years old) ;-)
But your fuzzy ideas are probably very interesting for them
Math/Informatics department
Will try to contact my colleagues to inform them ...

Have a nice day (here it is 35 deg C warm ;-( )
Peter




Op wo 26 jun. 2019 om 13:04 schreef Andreas Zeller <notifications@github.com

**Comment by andreas-zeller** [comment]
Sorry, thought this was in the notebooks to download; this is what I fixed.  You're talking about the interactive notebooks ("Edit as Notebook"), right?  I'll take a look into this.

**Comment by PKHG** [comment]
yes jupyternotebook python 3.7 ..by the way, admired the grammar pictures ..
really nice
 Andreas Zeller klingt ganz und gar deutsch, bin nach NL ausgewandert vor
beinahe genau 50 Jahren ..
damals in Hamburg Prof. Collatz gehört und beeundert eas der Mathematiker
alles konnte 😉
tschüss
Peter

Op wo 26 jun. 2019 om 18:21 schreef Andreas Zeller <notifications@github.com
